name: ms_persist
description: A mixin that help you on handling model as a CRUD, you just need implement 3 overrides
version: 2.2.1
homepage: https://github.com/Marcus-Software/ms_persist

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ms_map_utils: ">=1.0.0 <2.0.0"
  path: ">=1.7.0 <2.0.0"
  path_provider: ">=2.0.0 <3.0.0"
  sembast_web: ">=2.0.0 <4.0.0"
  sembast_sqflite: ">=2.0.0 <3.0.0"
  sqflite: ">=2.0.0 <3.0.0"
  uuid: ">=3.0.0 <5.0.0"
  sqflite_common_ffi: ^2.3.6
  sembast: ^3.8.5+1
  meta: ^1.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: ^5.0.2
  mockito: any

flutter:

